services:
  # otel-collector:
  #   image: otel/opentelemetry-collector
  #   volumes:
  #     - ./configs/otel-collector-config.yaml:/etc/otelcol/config.yaml
  #   ports:
  #     - 1888:1888 # pprof extension
  #     - 8888:8888 # Prometheus metrics exposed by the Collector
  #     - 8889:8889 # Prometheus exporter metrics
  #     - 13133:13133 # health_check extension
  #     - 4317:4317 # OTLP gRPC receiver
  #     - 4318:4318 # OTLP http receiver
  #     - 55679:55679 # zpages extension
  #   networks:
  #     - appnet
  #   depends_on:
  #     - consul
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - appnet
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./configs:/etc/prometheus:ro
    depends_on:
      - cadvisor
      - consul
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - appnet
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
    networks:
    - appnet
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      # - "4317:4317"  
      # - "4318:4318"
    environment:
      - JAEGER_AGENT_HOST=jaeger
    networks:
      - appnet
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - appnet
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - appnet
  consul:
    image: hashicorp/consul
    container_name: service-discovery
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
  gateway:
    build:
      context: .
      dockerfile: services.dockerfile
      args:
        SERVICE_DIR: gateway/cmd
    ports:
      - "8081:8081"
    restart: always
    env_file:
      - secrets.env
    depends_on:
      - consul
      - jaeger
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
    
  metadata:
    build:
      context: .
      dockerfile: services.dockerfile
      args:
        SERVICE_DIR: metadata/cmd
    ports:
      - "8083:8083"
    env_file:
      - secrets.env
    restart: always
    depends_on:
      - consul
      - jaeger
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
  compression:
    build:
      context: .
      dockerfile: services.dockerfile
      args:
        SERVICE_DIR: compression/cmd
    ports:
      - "8082:8082"
      - "8091:8091"
    env_file:
      - secrets.env
    restart: always
    depends_on:
      - consul
      - jaeger
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
  video:
    build:
      context: .
      dockerfile: services.dockerfile
      args:
        SERVICE_DIR: video/cmd
    ports:
      - "8084:8084"
    env_file:
      - secrets.env
    restart: always
    depends_on:
      - consul
      - jaeger
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
networks:
  appnet:
    driver: bridge
    name: appnet
volumes:
  shared:
  configs:
    