


services:
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - appnet
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - appnet
  consul:
    image: hashicorp/consul
    container_name: service-discovery
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
  gateway:
    build:
      context: .
      dockerfile: services.dockerfile
      args:
        SERVICE_DIR: browser-gateway/cmd
    ports:
      - "8085:8085"
    restart: always
    env_file:
      - secrets.env
    depends_on:
      - consul
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
    
  metadata:
    build:
      context: .
      dockerfile: services.dockerfile
      args:
        SERVICE_DIR: metadata/cmd
    ports:
      - "8082:8082"
    env_file:
      - secrets.env
    restart: always
    depends_on:
      - consul
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
  compression:
    build:
      context: .
      dockerfile: services.dockerfile
      args:
        SERVICE_DIR: compression/cmd
    ports:
      - "8081:8081"
    env_file:
      - secrets.env
    restart: always
    depends_on:
      - consul
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
  video:
    build:
      context: .
      dockerfile: services.dockerfile
      args:
        SERVICE_DIR: video/cmd
    ports:
      - "8083:8083"
    env_file:
      - secrets.env
    restart: always
    depends_on:
      - consul
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
networks:
  appnet:
    driver: bridge
    name: appnet
volumes:
  shared:
    